### ISSUE TITLE
[FEATURE] Bootstrapping for Microsoft Azure

### ISSUE THREAD

**Issue by benkoller** [maiot-io/zenml#32]
**Is your feature request related to a problem? Please describe.**
Users need to quickly get set up with using Azure with ZenML.

**Describe the solution you'd like**
To take bootstrapping of a cloud provider to the next level, a few functionalities can/should be built-in:

* integration of bootstrapping to the CLI (vs. independent terraform scripts)
* Inputs to bootstrap existing resources (e.g. an existing K8S cluster, reusing an existing MySQL)
* Automatic provisioning of the ZenML config
  * would require some additional information to be stored in the config, e.g. k8s details
* an easy way to share the setup config with other team members (e.g. hot-loading of a zenml config)
* "saved environments" to chose as backends.

**Describe alternatives you've considered**
Using Native APIs rather than Terraform - but these seem very hard to maintain

**Additional context**
Should follow the same logic as GCP logic [here](https://github.com/maiot-io/zenml/tree/main/examples/bootstrapping/gcp)

**Comment by htahir1** [comment]
As this issue is open for a few weeks now, and the main contributors have not been able to prioritize this ticket, we have decided to take this feature request into the [ROADMAP](https://github.com/maiot-io/zenml/blob/main/ROADMAP.md). This maintains transparency, while also clearing up the issue board, which can then be a place for more short-term or WIP features/bugs/enhancements etc.
