### ISSUE TITLE
[ENHANCEMENT] Distribute requirements.txt into folder wise structure

### ISSUE THREAD

**Issue by ramitsurana** [maiot-io/zenml#80]
**Is your enhancement request related to a problem? Please describe.**
No 

**Describe the enhancement you'd like**
I was going through this [File](https://github.com/maiot-io/zenml/blob/main/zenml/utils/requirement_utils.py) and wanted to check your thoughts if we could create a folder wise tree-like structure for different requirements like extensions, providers etc. in text files, depending on our use case and refer to the path of the requirements files from contants.py. Let me know if you see any challenges. For Example - 

```
requirements
-> base.txt
-> providers
    -> gcp.txt
    -> azure.txt
    -> aws.txt
-> datasources
    -> huggingface.txt
```

**How do you solve your current problem with the current status-quo of ZenML?**
It would make it easier to update and maintain the versions of dependencies including extensions, base dependencies etc rather than updating the python file for any version updates.

**Additional context**
<img width="341" alt="enhance" src="https://user-images.githubusercontent.com/8342133/116075249-57a7c600-a6b0-11eb-8977-0346be6b773c.PNG">

**Comment by bcdurak** [comment]
Hey @ramitsurana , thank you for opening this issue. 

The integrations are an essential part of ZenML and it is definitely important to keep the requirements of each integration as organized as possible. However, with the increasing number of integrations, it will become more and more challenging to place them in clear-cut categories. Huggingface is a great example of this particular problem because we use it both as a datasource and as a training integration. That is why we opted to keep the requirements in a single central file.
